# SPDX-FileCopyrightText: 2026 ash_judgments contributors <https://github.com/lukegalea/ash_judgments>
#
# SPDX-License-Identifier: MIT

defmodule AshJudgments.Ledger.Fragment do
  @moduledoc """
  The judgment-ledger fragment: the attributes, actions and pure derived
  changes a host includes in its own resource.

  The package never defines the persisted resource — the host includes
  this fragment on its platform base so the host's audit, tenancy and
  ownership apply (see `AshJudgments.Ledger` for the host shape).

  ## Replay safety is structural (RFC §6.1)

  The `:record` create **accepts every field as input, including the
  answer**. Its only changes compute pure derived fields from those
  inputs — the cache key, the record hash, the stack region from config —
  all of which are identical on replay. There is no I/O, no clock read
  for an identity field, and no instrument call anywhere on the create
  path: during AshEvents replay the same inputs rebuild the same row and
  no model is consulted. `recorded_at` is the one database-generated
  field (declare it as the resource's `create_timestamp` in the events
  config; AshEvents restores it on replay).

  ## Actions

  - **`:record`** — the create. Takes every field, including the caller-
    generated observation `id` (RFC §4.1: generated before the instrument
    is called, so a retry cannot write two rows for one call).
  - **`:tombstone_state`** — the ONE sanctioned update (ADR 0024
    erasure): clears the reserved state payload, keeps the digests.
    Observations are otherwise immutable — re-inference is a new row
    (law 2).
  - **`:by_cache_key`** / **`:by_subject`** — the reads CORE-CACHE and
    the fact builder build on.

  ## Fields (RFC §5; the ticket's frozen list)

  Every field is envelope-class unless noted. The state payload is
  digest-plus-reference by default: `state_digest` and `state_ref`
  travel; `state_ciphertext` is the reserved payload slot
  (DEC-PRIVACY-deferred) that `:tombstone_state` clears.
  """

  @moduledoc since: "0.1.0"

  use Spark.Dsl.Fragment, of: Ash.Resource

  require Ash.Query

  alias AshJudgments.Ledger

  attributes do
    # The observation id is generated by the CALLER before the instrument
    # is called and passed in (RFC §4.1) — writable, with a default for
    # callers that do not care.
    attribute :id, :uuid,
      primary_key?: true,
      allow_nil?: false,
      default: &Ash.UUID.generate/0,
      writable?: true,
      public?: true

    # The one database-generated field (RFC §5.6); AshEvents restores it
    # on replay (declare as the events config's create_timestamp).
    create_timestamp :recorded_at

    attribute :record_version, :string,
      default: "0",
      writable?: false,
      public?: true,
      description: "The record schema version, major only (RFC §11)."

    attribute :record_hash, :string,
      writable?: true,
      public?: true,
      description:
        "Digest of the record's own canonical JSON minus record_hash minus payload fields (RFC §4.5); computed by the :record change from inputs."

    ## Question (§5.2) — identity hangs off the registry.

    attribute :question_id, :string, allow_nil?: false, public?: true
    attribute :question_hash, :string, allow_nil?: false, public?: true
    attribute :question_version, :integer, allow_nil?: false, public?: true
    attribute :family, :string, allow_nil?: false, public?: true

    ## Subject (§5.4) — denormalised for queries.

    attribute :subject_type, :string, public?: true
    attribute :subject_id, :string, public?: true
    attribute :rule_id, :string, public?: true
    attribute :predicate_id, :string, public?: true
    attribute :atom_ids, {:array, :string}, public?: true
    attribute :document_hash, :string, public?: true
    attribute :parser_version, :string, public?: true

    ## State (§5.4) — digest plus reference; the payload slot is reserved.

    attribute :state_digest, :string, allow_nil?: false, public?: true
    attribute :state_ref, :map, public?: true

    attribute :state_ciphertext, :binary,
      public?: false,
      description:
        "Reserved state payload (DEC-PRIVACY-deferred, per family). Payload class: outside record_hash, cleared by :tombstone_state."

    ## Answer (§5.5) — accepted as input; a failure is still an observation.

    attribute :answer_kind, :atom,
      allow_nil?: false,
      public?: true,
      # The frozen record's closed kind enum (§5.5, schema.json):
      # `evidence` is the §5.4 evidence-work kind, `extraction` the
      # extract→verify kind.
      constraints: [one_of: [:noul, :choice, :score, :evidence, :extraction]]

    attribute :value, :string,
      public?: true,
      description:
        "The collapsed value as a decimal-string discipline value: the Choice/evidence option, the Score position, nil for a Noul (Q9: a noul has no collapsed value)."

    attribute :probabilities, :map,
      public?: true,
      description:
        "The distribution: option (or level index) -> decimal string. For a Noul, derived by the :record change from its probability."

    attribute :confidence, :decimal, public?: true

    ## Instrument (§5.3) — identity as digests, never endpoints (§9).

    attribute :model_spec_requested, :string,
      allow_nil?: false,
      public?: true,
      description: "The model name as requested — without base_url or keys (§9)."

    attribute :model_version, :string,
      public?: true,
      description:
        "What the runtime reported as answered (nil allowed; pinned families get it at banding)."

    attribute :model_digest, :string, public?: true
    attribute :runtime_version, :string, public?: true
    attribute :profile, :string, allow_nil?: false, public?: true

    attribute :residency, :atom,
      public?: true,
      constraints: [one_of: [:in_cluster, :sub_processor]],
      default: :in_cluster

    ## Call (§5.6).

    attribute :usage, :map, public?: true
    attribute :latency_us, :integer, public?: true

    attribute :cache_key, :string,
      allow_nil?: false,
      writable?: true,
      public?: true,
      description:
        "Computed by the :record change from inputs — the full §4.4 key (see AshJudgments.Cache.key/1)."

    attribute :wire_question_hash, :string,
      public?: true,
      description:
        "Digest of the canonical JSON of the exact question object sent (§3.3) — in the §4.4 cache key; the declared question_hash identifies the wording, this identifies the call."

    attribute :shadow_of, :uuid,
      public?: true,
      description:
        "Shadow rows only: the live observation this candidate call shadows (§5.6). Shadow rows are never banded and never materialise."

    attribute :mode, :atom,
      allow_nil?: false,
      public?: true,
      constraints: [one_of: [:live, :shadow, :calibration, :eval]],
      default: :live

    attribute :region, :string,
      allow_nil?: false,
      writable?: true,
      public?: true,
      description:
        "The stack's region (law 10) — host config, set by the :record change, never a caller input."

    attribute :correlation_id, :uuid, public?: true

    ## Envelope (§5.2) — the provenance-envelope embed (AST-9). Placeholder
    ## until that struct exists; hosts that fill it pass the map.
    attribute :envelope, :map, public?: false

    attribute :valid_until, :utc_datetime_usec,
      public?: true,
      description: "Compliance expiry — a fact builder reads nothing past it (AST-93)."
  end

  actions do
    create :record do
      description """
      Records an observation. Accepts every field as input, including the
      answer — the instrument was called before this action, and replay
      rebuilds the row from these inputs without ever consulting a model
      (law 2, RFC §6.1).
      """

      accept [
        :id,
        :question_id,
        :question_hash,
        :question_version,
        :family,
        :subject_type,
        :subject_id,
        :rule_id,
        :predicate_id,
        :atom_ids,
        :document_hash,
        :parser_version,
        :state_digest,
        :state_ref,
        :state_ciphertext,
        :answer_kind,
        :value,
        :probabilities,
        :confidence,
        :model_spec_requested,
        :model_version,
        :model_digest,
        :runtime_version,
        :profile,
        :residency,
        :usage,
        :latency_us,
        :wire_question_hash,
        :shadow_of,
        :mode,
        :correlation_id,
        :envelope,
        :valid_until
      ]

      # Pure derived fields from inputs only (RFC §6.1): identical on
      # replay, no I/O, no clock.
      change {AshJudgments.Ledger.Changes.DeriveRecord, []}
    end

    update :tombstone_state do
      description """
      ADR 0024 erasure: clears the reserved state payload and keeps the
      digests, so replay and audit still verify. The one sanctioned update
      on an otherwise immutable row.
      """

      accept []
      change {AshJudgments.Ledger.Changes.TombstoneState, []}
    end

    read :by_cache_key do
      description "The cache lookup (CORE-CACHE builds its modes on this)."
      get? true

      argument :cache_key, :string, allow_nil?: false, public?: true

      filter expr(cache_key == ^arg(:cache_key))
    end

    read :by_subject do
      description "Every recorded observation for a subject, newest first; optionally one question."

      argument :subject_type, :string, allow_nil?: false, public?: true
      argument :subject_id, :string, allow_nil?: false, public?: true
      argument :question_id, :string, public?: true

      filter expr(subject_type == ^arg(:subject_type) and subject_id == ^arg(:subject_id))

      prepare build(load: [:question_id])

      prepare fn query, _ ->
        case query.arguments[:question_id] do
          nil -> query
          question_id -> Ash.Query.filter(query, expr(question_id == ^question_id))
        end
      end
    end

    defaults [:read]
  end

  identities do
    # The observation id is the caller's idempotency key (RFC §4.1).
    identity :unique_id, [:id]
  end
end

defmodule AshJudgments.Ledger.Changes.DeriveRecord do
  @moduledoc false
  # The :record create's derived fields — PURE functions of the inputs
  # plus stack config (RFC §6.1): identical on replay, no I/O, no clock.
  #
  # - cache_key: AshJudgments.Ledger.cache_key/1 (model version ‖ question
  #   hash ‖ state digest, at v0 fidelity).
  # - record_hash: the §4.5 digest over the envelope-class fields.
  # - region: the stack's configured region (law 10) — host config, not a
  #   caller input, identical on replay. A missing region fails the write
  #   here AND at boot (AshJudgments.Ledger.region!/0 for hosts).

  use Ash.Resource.Change

  alias AshJudgments.Ledger

  @impl true
  def change(changeset, _opts, _context) do
    region = Ledger.region!()

    changeset
    |> Ash.Changeset.change_attribute(:region, Atom.to_string(region))
    |> Ash.Changeset.before_action(fn changeset ->
      cache_key =
        Ledger.cache_key(%{
          state_digest: Ash.Changeset.get_attribute(changeset, :state_digest),
          model_digest: Ash.Changeset.get_attribute(changeset, :model_digest),
          runtime_version: Ash.Changeset.get_attribute(changeset, :runtime_version),
          wire_question_hash: Ash.Changeset.get_attribute(changeset, :wire_question_hash),
          zone_id: region
        })

      record_hash =
        Ledger.record_hash(%{
          question_id: Ash.Changeset.get_attribute(changeset, :question_id),
          question_hash: Ash.Changeset.get_attribute(changeset, :question_hash),
          question_version: Ash.Changeset.get_attribute(changeset, :question_version),
          family: Ash.Changeset.get_attribute(changeset, :family),
          subject_type: Ash.Changeset.get_attribute(changeset, :subject_type),
          subject_id: Ash.Changeset.get_attribute(changeset, :subject_id),
          state_digest: Ash.Changeset.get_attribute(changeset, :state_digest),
          state_ref: Ash.Changeset.get_attribute(changeset, :state_ref),
          answer_kind: Ash.Changeset.get_attribute(changeset, :answer_kind),
          value: Ash.Changeset.get_attribute(changeset, :value),
          probabilities: Ash.Changeset.get_attribute(changeset, :probabilities),
          confidence: Ash.Changeset.get_attribute(changeset, :confidence),
          model_spec_requested: Ash.Changeset.get_attribute(changeset, :model_spec_requested),
          wire_question_hash: Ash.Changeset.get_attribute(changeset, :wire_question_hash),
          model_version: Ash.Changeset.get_attribute(changeset, :model_version),
          model_digest: Ash.Changeset.get_attribute(changeset, :model_digest),
          runtime_version: Ash.Changeset.get_attribute(changeset, :runtime_version),
          profile: Ash.Changeset.get_attribute(changeset, :profile),
          residency: Ash.Changeset.get_attribute(changeset, :residency),
          mode: Ash.Changeset.get_attribute(changeset, :mode),
          region: Atom.to_string(region),
          correlation_id: Ash.Changeset.get_attribute(changeset, :correlation_id),
          valid_until: Ash.Changeset.get_attribute(changeset, :valid_until)
        })

      changeset
      |> Ash.Changeset.force_change_attribute(:cache_key, cache_key)
      |> Ash.Changeset.force_change_attribute(:record_hash, record_hash)
    end)
  end
end

defmodule AshJudgments.Ledger.Changes.TombstoneState do
  @moduledoc false
  # ADR 0024 erasure: the state payload goes; the digests stay. Pure from
  # the inputs (there are none) — replay-safe by construction.
  use Ash.Resource.Change

  @impl true
  def change(changeset, _opts, _context) do
    Ash.Changeset.after_action(changeset, fn _changeset, result ->
      AshJudgments.Telemetry.tombstoned(result.id)
      {:ok, result}
    end)
    |> then(fn changeset ->
      Ash.Changeset.change_attribute(changeset, :state_ciphertext, nil)
    end)
  end
end
